name: ci-pull-request
on:
  pull_request:
    branches:
      - main
jobs:
  test-migrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Test DB Migrations
        run: |
          echo ${{ job.services.postgres.ports[5432] }}
          npm install
          npm run knex:migrate:latest -- --connection "postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}"
          npm run knex:migrate:rollback -- --connection "postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}"
